# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3.10
fail_fast: false
exclude: /(|migrations)/

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories, ".:my_health_diary", --py38-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.2
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length, "100", "--ignore=E203,F401,F841,W503"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']
